version : 2.x.{build}

clone_folder: C:\Project

environment:
    global:
        # MSVC Express 2008's setenv.cmd failes if /E:ON and /V:ON are not
        # enabled in the batch script interpreter
        CMD_IN_ENV: cmd /E:ON /V:ON /C .\appveyor\run_with_env.cmd

    matrix:
        # For Python versions available on Appveyor, see
        # https://www.appveyor.com/docs/build-environment/
      - {PYVER: "27", PYTHON_ARCH: "32"}
      - {PYVER: "27", PYTHON_ARCH: "64"}
      - {PYVER: "37", PYTHON_ARCH: "32"}
      - {PYVER: "37", PYTHON_ARCH: "64"}
      - {PYVER: "36", PYTHON_ARCH: "32"}
      - {PYVER: "36", PYTHON_ARCH: "64"}
      - {PYVER: "35", PYTHON_ARCH: "32"}
      - {PYVER: "35", PYTHON_ARCH: "64"}
      - {PYVER: "34", PYTHON_ARCH: "32"}
      - {PYVER: "34", PYTHON_ARCH: "64"}

    OPENSSL_VERSION: "1_1_1b"
    POSTGRES_VERSION: "11_2"

    PSYCOPG2_TESTDB: psycopg2_test
    PSYCOPG2_TESTDB_USER: postgres
    PSYCOPG2_TESTDB_HOST: localhost

    PGUSER: postgres
    PGPASSWORD: Password12!

    # The python used in the build process, not the one packages are built for
    PYEXE: C:\Python36\python.exe

matrix:
    fast_finish: false

services:
    # Note: if you change this service also change the paths to match
    # (see where Program Files\Postgres\9.6 is used)
    - postgresql96

cache:
  # Rebuild cache if following file changes
  # (See the file to zap the cache manually)
  - C:\Others -> scripts\appveyor.cache_rebuild

# Script called before repo cloning
init:
    # TODO: move functionalities out of init to drop this fetch problem
    - curl -fsSL -o "C:\\appveyor.py" https://raw.githubusercontent.com/psycopg/psycopg2/%APPVEYOR_REPO_COMMIT%/scripts/appveyor.py
    - "%PYEXE% C:\\appveyor.py init"

# Repository gets cloned, Cache is restored

install:
    - "%PYEXE% C:\\appveyor.py install"

# PostgreSQL server starts now

build: off

build_script:
    - "%PYEXE% C:\\appveyor.py build_script"

after_build:
    - "%PYEXE% C:\\appveyor.py after_build"

before_test:
    - "%PYEXE% C:\\appveyor.py before_test"

test_script:
    - "%PYEXE% C:\\appveyor.py test_script"


# vim: set ts=4 sts=4 sw=4:
